### ISSUE TITLE
flask app running on one server and Identity service running on a different server

### ISSUE THREAD

**Issue by indera** [inveniosoftware/flask-sso#13]
I was reading the 
http://flask-sso.readthedocs.org/en/latest/#a-minimal-example
and I was wondering if I can use the flask-sso library to restrict access to my own app.

Basically I want to have a login button on my flask app which when clicked redirects the user to a third-party server where the actual username and password is entered then the user is allowed to browse restricted content in the flask app.

**Comment by jirikuncar** [comment]
You need to generate your login button to the external service yourself.

*Example*
```jinja
<a href="https://sso.example.com/?redirect={{ url_for(current_app.config.SSO_LOGIN_ENDPOINT, _external=True) }}">Login</a>
```

And for authentication you can use *Flask-SSO* in combination with *Flask-Login* or *Flask-Security*.

**Comment by indera** [comment]
Thank you for the prompt answer. I will give it a try and update the docs if I succeed :)

**Comment by jirikuncar** [comment]
I missed the notification sorry. You can check our docs: http://flask-sso.readthedocs.io/en/latest/#sso-login-endpoint

```
app.config.setdefault('SSO_LOGIN_ENDPOINT', 'sso_login')
```
